/**
 * Le catalan, traduit pour de bon.
 *
 * La version catalane n'existait que de nom : elle reprenait le bloc espagnol
 * et ne traduisait que le menu et quelques titres. Un visiteur qui choisissait
 * « CA » lisait donc de l'espagnol, ce qui vaut mieux que rien mais ne tient
 * pas la promesse du drapeau.
 *
 * Tout est ici, dans l'ordre du bloc espagnol dont il est la traduction. Les
 * noms de marque, les identifiants techniques, les adresses de documents et
 * les chiffres ne changent jamais d'une langue à l'autre : seuls les mots
 * autour d'eux sont traduits.
 */

export const ca = {
  waterCalculator: {
    eyebrow: "Simulador",
    title: "Calculeu el vostre estalvi d'aigua",
    lede: "Indiqueu les dades de la vostra explotació per estimar l'estalvi que podeu assolir amb els nostres hidroretenidors, segons el vostre sistema de reg actual.",
    surfaceLabel: "Superfície conreada",
    surfaceUnit: "ha",
    irrigationLabel: "Sistema de reg actual",
    irrigationModes: ["Degoteig", "Aspersió", "Pívot", "Gravetat / inundació", "Altre"],
    consumptionLabel: "Consum actual",
    consumptionUnit: "m³/ha",
    resultEyebrow: "Estalvi estimat en una campanya",
    resultNote: "Marge baix a alt, segons el sistema de reg",
    poolsPrefix: "l'equivalent de",
    poolsSuffix: "piscines olímpiques",
    disclaimer:
      "Estimació indicativa basada en els estalvis d'aigua documentats dels nostres hidroretenidors (−40 a −70 % segons el sistema de reg). El resultat real depèn del sòl, del clima i del conreu. Aquesta eina dóna un ordre de magnitud: en cap cas aquestes xifres es poden considerar un valor garantit, contractual o absolut.",
  },
  doseCalculator: {
    eyebrow: "Calculadora de dosi",
    title: "Quant EVERGREEN® necessita la vostra parcel·la",
    lede: "Indiqueu la localització, el conreu i la parcel·la. El càlcul de la dosi no depèn de les dades d'aigua: aquestes només afinen l'estimació d'estalvi.",
    locationTitle: "Localització",
    countryLabel: "País",
    regionLabel: "Regió / província",
    cityLabel: "Ciutat o localitat propera",
    detectButton: "Actualitzar la localització i el clima",
    detecting: "Detectant…",
    climateHead: "Condicions climàtiques registrades",
    latitude: "Latitud",
    altitude: "Altitud",
    zone: "Zona",
    rainfall: "Pluviometria",
    temperature: "Temperatura",
    stress: "Estrès",
    climateUnavailable:
      "Clima no disponible per a aquesta localitat. La dosi es continua calculant amb els paràmetres agronòmics.",
    zones: {
      tropical: "Tropical",
      subtropical: "Subtropical",
      temperate: "Temperada",
      cold: "Freda",
    },
    stressLevels: { normal: "Normal", moderate: "Moderat", high: "Alt" },
    plotTitle: "Parcel·la i conreu",
    cropLabel: "Conreu",
    soilLabel: "Tipus de sòl",
    irrigationLabel: "Sistema de reg",
    areaLabel: "Superfície conreada (ha)",
    densityLabel: "Densitat (plantes/ha, opcional)",
    spacingLabel: "Distància entre fileres (m, opcional)",
    optionalPlaceholder: "Deixeu-ho en blanc si no ho sabeu",
    soils: {
      unknown: "Desconegut",
      sandy: "Sorrenc",
      sandyLoam: "Franc sorrenc",
      loam: "Franc",
      clayLoam: "Franc argilós",
      clay: "Argilós",
    },
    irrigations: {
      rainfed: "Secà",
      drip: "Degoteig",
      sprinkler: "Aspersió",
      pivot: "Pívot central",
      flood: "Gravetat / inundació",
      other: "Altre",
    },
    waterTitle: "Aigua",
    waterUseLabel: "Consum actual (m³/ha/campanya)",
    waterUsePlaceholder: "En blanc si és secà o no ho sabeu",
    waterPriceLabel: "Preu de l'aigua (€/m³)",
    waterHint:
      "Aquests dos camps són opcionals. No modifiquen mai la dosi: només serveixen per quantificar l'estalvi d'aigua.",
    resultsTitle: "Resultats",
    doseLabel: "Dosi recomanada",
    doseEstimated: "Densitat estimada a partir de les nostres referències",
    doseFromInput: "Càlcul amb el valor que heu indicat",
    doseStress: "dosi d'estrès aplicada",
    totalLabel: "Necessitat total d'EVERGREEN®",
    totalTonnesPrefix: "és a dir",
    waterSavingLabel: "Estalvi d'aigua estimat",
    waterPending: "Per calcular",
    waterNoConsumption: "Indiqueu el vostre consum per obtenir un volum",
    yieldLabel: "Potencial de producció",
    yieldStudy: "Cal un estudi de camp",
    yieldStudyNote:
      "En un cereal extensiu o una gramínia, només un estudi de camp permet una estimació seriosa: la resposta depèn massa de l'itinerari tècnic.",
    yieldRangeNote: "Marge propi d'aquest conreu, pendent de consolidar amb els assajos en curs.",
    yieldDefaultNote:
      "Marge indicatiu per defecte, a falta d'una referència consolidada per a aquest conreu.",
    to: "a",
    disclaimer:
      "Estimació indicativa. La dosi depèn del sòl, del clima, del conreu i de l'itinerari tècnic real de la parcel·la. Aquesta eina dóna un ordre de magnitud: en cap cas aquestes xifres es poden considerar un valor garantit, contractual o absolut.",
  },
  nav: {
    approach: "El nostre enfocament",
    technologies: "Tecnologies",
    trials: "Assajos",
    proofs: "Proves",
    network: "Xarxa",
    resources: "Recursos",
    fieldTests: "Proves de camp",
    partners: "Socis",
    contact: "Escriu-nos",
    openMenu: "Obre el menú",
    closeMenu: "Tanca el menú",
  },
  hero: {
    slogan1: "Cultivar més",
    slogan2: "amb menys aigua",
    slogan3: "naturalment",
    explore: "Explorar",
    calculatorCta: "Calculeu l'estalvi d'aigua",
    quoteCta: "Demanar un pressupost",
    doseCta: "Calculeu la vostra dosi",
    whereTo1: "El nostre enfocament",
    whereTo2: "Tecnologies?",
  },
  proofBar: [
    { figure: "+30 a +100 %", label: "de rendiment, en quantitat i en qualitat" },
    { figure: "−40 a −70 %", label: "de necessitat d'aigua de reg" },
    { figure: "15", label: "assajos pilot en curs el 2026" },
    { figure: "SOHISCERT", label: "i EU Bio, certificacions reals" },
  ],
  presentation: {
    eyebrow: "El nostre enfocament",
    title1: "Les nostres cinc tecnologies",
    title2: "Un objectiu",
    title3: "El creixement i la qualitat",
    lede: "Green Solutions desenvolupa i distribueix tecnologies agrícoles disruptives, pensades per augmentar la productivitat tot preservant, i fins i tot regenerant, els recursos naturals dels quals depèn aquesta productivitat. Respostes concretes, provades al camp, davant l'estrès hídric, l'esgotament dels sòls, la rendibilitat i la seguretat alimentària.",
    tagline:
      "Totes les nostres solucions disruptives es poden fer servir en qualsevol planta i conreu, sota qualsevol clima i en qualsevol tipus de sòl!",
    stats: [
      { num: "30", label: "socis" },
      { num: "39", label: "països" },
      { num: "5", label: "tecnologies de marca" },
    ],
    distinguish: [
      {
        num: "01",
        title: "Certificat, no només anunciat",
        text: "SOHISCERT · EU Bio, compatible amb l'agricultura ecològica.",
      },
      {
        num: "02",
        title: "Provat al camp",
        text: "60 països per a ECOFERT® · 55+ països per a Water Vital®.",
      },
      {
        num: "03",
        title: "Zero contaminació",
        text: "Polímers totalment degradables · zero residus tòxics al sòl, a l'aire o a l'aigua.",
      },
      {
        num: "04",
        title: "Tecnologies que es reforcen entre si",
        text: "Cadascuna aixeca la limitació de la següent. Es venen per separat, pensades juntes.",
      },
    ],
  },
  tenirAvancer: {
    eyebrow: "Què us porta aquí?",
    title1: "Dues direccions possibles:",
    title2: "Intentar sobreviure d'una banda, avançar de l'altra.",
    tabLabel: "Aguantar o avançar",
    tabTenir: "01 · No canviar res",
    tabAvancer: "02 · Reaccionar i guanyar",
    tenirList: [
      "L'aigua de reg escasseja i costa més cara",
      "Els sòls perden estructura i fertilitat",
      "El cost dels insums es menja el marge",
      "La normativa sobre pesticides s'endureix",
    ],
    avancerList: [
      {
        text: "Augmentar els rendiments sense la factura de l'aigua: els nostres hidroretenidors i la nostra aigua reestructurada redueixen la necessitat de reg entre un 40 i un 70 %, mantenint, i fins i tot augmentant, els vostres rendiments.",
        linkLabel: "Veure EVERGREEN® i ECOSORB®",
        linkHref: "#retention-eau",
      },
      {
        text: "Complir els requisits ecològics i de certificació: ECOFERT® està certificat per SOHISCERT i EU Bio, i ja s'utilitza en 60 països, per respondre als plecs més estrictes sense sacrificar el rendiment.",
        linkLabel: "Veure ECOFERT®",
        linkHref: "#fertilisation",
      },
      {
        text: "Fer rendir una terra recuperada: el nostre programa d'agrosilvicultura instal·la un ecosistema funcional en menys de 24 mesos, fins i tot en sòls sorrencs o degradats, amb cada planta equipada des del moment de plantar-la.",
        linkLabel: "Veure l'agrosilvicultura",
        linkHref: "#agroforesterie",
      },
      {
        text: "Fer rendible la reforestació: el Paulownia ALTIFOLIA® arriba als 13-15 m en sis a vuit anys, i fins a 20 m després, i la seva fusta es valora al voltant de 550 €/m³, amb una rendibilitat al llarg de sis anys de conreu.",
        linkLabel: "Veure Paulownia ALTIFOLIA®",
        linkHref: "#paulownia",
      },
    ],
    cta: "Són aquestes les vostres preocupacions?",
  },
  products: {
    eyebrow: "Les tecnologies",
    title: "Una resposta a cada limitació del camp",
    lede: "Cinc tecnologies de marca, i el programa d'agrosilvicultura que les combina a les terres per recuperar.",
    moreInfo: "Més informació",
    videosHeading: "En vídeo",
    watchVideo: "Vídeo",
    readMore: "Saber-ne més",
    readLess: "Veure'n menys",
    items: [
      {
        id: "retention-eau",
        num: "01",
        kicker: "Retenir l'aigua",
        title: "EVERGREEN® & ECOSORB®",
        text: "Els nostres hidroretenidors capten l'aigua de pluja o de reg i l'emmagatzemen en forma de gel ben a prop de les arrels, sense alterar-ne la qualitat. Un dipòsit permanent, accessible per a la planta sigui quin sigui el sòl o el clima, que elimina l'estrès hídric en les fases crítiques del cicle.",
        facts: [
          "−40 a −70 % d'aigua segons el tipus de reg",
          "EVERGREEN®: unes 300 vegades el seu pes en aigua, 3 a 4 anys al sòl",
          "ECOSORB®: unes 300 vegades el seu pes, base de midó de blat de moro, 2 a 3 anys",
          "Es degrada del 20 al 25 % l'any, sense risc de sobredosi",
          "Canya de sucre: +25 % de contingut de sucre (Brix) amb 15 kg/ha",
        ],
        more: "EVERGREEN® i ECOSORB® són polímers superabsorbents que es biodegraden completament, sense deixar residus al sòl ni a les plantes. Absorbeixen unes 300 vegades el seu pes en aigua i la retornen a les arrels segons les necessitats del conreu, cicle rere cicle, fins a degradar-se de manera natural (20 a 25 % l'any) en CO₂, aigua i compostos nitrogenats assimilables. A diferència dels hidroretenidors a base de sodi —que, un cop hidratats, formen una pasta salada que ofega les arrels— o de les formulacions a base d'acrilamida, prohibides en molts països per la seva toxicitat, les nostres dues referències són a base de potassi i compatibles amb els conreus alimentaris. En contacte amb l'aigua, el gra sec s'omple i s'infla: aquest anar i venir descompacta el sòl com ho faria un cuc de terra, en millora la permeabilitat i crea un microclima humit propici per a la microfauna i la microflora, motors de la fertilitat natural. Els fertilitzants dissolts queden retinguts al pas en lloc de filtrar-se cap als aqüífers, cosa que redueix la contaminació i permet aprofitar millor cada aportació. Combinats amb els nostres fertilitzants ECOFERT®, EVERGREEN® i ECOSORB® formen un sistema complet que va permetre, en canya de sucre, un guany del 25 % en grau de sucre (Brix) amb només 15 kg de producte per hectàrea. Més del 95 % de les plantes trasplantades amb els nostres hidroretenidors arrelen, molt per damunt de les taxes convencionals.",
        detail: {
          sections: [
            {
              h: "El principi",
              p: "EVERGREEN® i ECOSORB® són polímers superabsorbents que es biodegraden completament, sense deixar residus al sòl ni a les plantes. Absorbeixen unes 300 vegades el seu pes en aigua i la retornen a les arrels segons les necessitats del conreu, cicle rere cicle, fins a degradar-se de manera natural (20 a 25 % l'any) en CO₂, aigua i compostos nitrogenats assimilables. A diferència dels hidroretenidors a base de sodi o de les formulacions a base d'acrilamida, prohibides en molts països per la seva toxicitat, les nostres dues referències són a base de potassi i compatibles amb els conreus alimentaris. En contacte amb l'aigua, el gra sec s'omple i s'infla: aquest anar i venir descompacta el sòl com ho faria un cuc de terra, en millora la permeabilitat i crea un microclima humit propici per a la microfauna i la microflora, motors de la fertilitat natural. Els fertilitzants dissolts queden retinguts al pas en lloc de lixiviar-se cap als aqüífers, cosa que redueix la contaminació i permet aprofitar millor cada aportació. Combinats amb els nostres fertilitzants ECOFERT®, formen un sistema complet que va permetre, en canya de sucre, un guany del 25 % en grau de sucre (Brix) amb només 15 kg per hectàrea. Més del 95 % de les plantes trasplantades amb els nostres hidroretenidors arrelen, davant d'una taxa clarament menor en condicions convencionals.",
            },
            {
              h: "El mecanisme, en detall",
              p: "En contacte amb l'aigua —de pluja, de reg o la humitat que queda al sòl— el gra sec absorbeix unes 300 vegades el seu propi pes i es transforma en un gel que emmagatzema l'aigua ben a prop de les arrels. Les tres primeres setmanes de conreu són crítiques: cal mantenir un reg normal per saturar completament els grans, i durant aquest temps les arrels de les plantes s'entrellacen amb el gel i s'ancoren en aquesta reserva d'aigua. EVERGREEN® i ECOSORB® no són gens tòxics per a la pell; només la seva granulometria fina obliga a fer servir una mascareta antipols en manipular-los. Si es vessen, cal bufar els residus amb aire comprimit en lloc d'esbandir-los amb aigua, que deixaria el terra relliscós.",
            },
            {
              h: "On i com fer-los servir",
              p: "Els nostres hidroretenidors es fan servir tant en agricultura convencional com ecològica —de fet, acceleren la transició cap al bio certificat—, en arboricultura, en vivers, en jardineria i en agrosilvicultura. Més del 95 % dels arbres trasplantats arrelen: les pèrdues restants venen de plantes no viables o de danys causats per la fauna, mai de l'estrès hídric. Els camps de golf i els ajuntaments que els adopten expliquen que l'estalvi de mà d'obra de reg ja cobreix el cost del producte la primera temporada. N'hi ha prou de barrejar-los amb el substrat de plantació; són compatibles amb l'addició de fertilitzants, bioestimulants o bacteris, l'acció dels quals es veu reforçada per la presència constant d'aigua.",
            },
          ],
          gallery: [
            "Un mateix conreu, amb i sense hidroretenidor: la diferència davant l'estrès hídric.",
            "Els grànuls d'hidroretenidor, plens d'aigua, en contacte directe amb les arrels.",
            "EVERGREEN® i ECOSORB®, envasats i a punt per enviar.",
          ],
        },
      },
      {
        id: "fertilisation",
        num: "02",
        kicker: "Nodrir sense química",
        title: "Fertilitzants ECOFERT®",
        text: "Un fertilitzant en microdosis d'aminoàcids, nitrogen, fòsfor i potassi, procedent de recursos renovables. No quelant: no esgota el sòl, l'enriqueix. Sense lixiviació, sense augment de salinitat ni de nitrats, ni a la planta ni a la terra.",
        facts: [
          "Fins a +100 % de producció, en quantitat i en qualitat",
          "+60 % de rendiment documentat a la zona saheliana amb ECOSORB®",
          "1 a 4 flascons de 140 ml per hectàrea",
          "Certificat SOHISCERT i EU Bio, utilitzat en 60 països",
        ],
        more: "ECOFERT® és un fertilitzant líquid biològic en microdosis, compost d'aminoàcids lliures (8 %) i de nitrogen total (1,73 %), la major part en forma orgànica (1,66 %), amb un pH proper a 9. La seva fórmula combina lisina, arginina, treonina, glicina, isoleucina i leucina —aminoàcids que la planta pot assimilar directament i que l'acompanyen en les fases crítiques (floració, quallat) sense esgotar mai el sòl, a diferència dels fertilitzants quelants convencionals. Certificat per SOHISCERT i conforme al reglament europeu de producció ecològica (UE 2018/848), s'utilitza en una seixantena de països i es dosifica d'1 a 4 flascons de 140 ml per hectàrea —en general dues aplicacions per a fruiters, cítrics i hortalisses (una al sòl abans de la floració o de la sembra, una altra foliar a mitja campanya); a les zones tropicals es pot arribar a un flascó cada tres mesos. Segur de manipular, inflamable no ho és gens, i sense requisits especials de transport ni d'emmagatzematge, ECOFERT® combinat amb els nostres hidroretenidors EVERGREEN® i ECOSORB® ha permès documentar fins a un +100 % de producció a la zona saheliana, amb guanys de rendiment del +60 % mesurats sobre el terreny.",
        detail: {
          sections: [
            {
              h: "El principi",
              p: "ECOFERT® és un fertilitzant líquid biològic en microdosis, compost d'aminoàcids lliures (8 %) i de nitrogen total (1,73 %), la major part en forma orgànica (1,66 %), amb un pH proper a 9. La seva fórmula combina lisina, arginina, treonina, glicina, isoleucina i leucina —aminoàcids que la planta pot assimilar directament i que l'acompanyen en les fases crítiques sense esgotar mai el sòl, a diferència dels fertilitzants quelants convencionals. Certificat per SOHISCERT i conforme al reglament europeu de producció ecològica (UE 2018/848), s'utilitza en una seixantena de països.",
            },
            {
              h: "Una fórmula que no esgota mai el sòl",
              p: "A diferència dels fertilitzants quelants convencionals, l'ús prolongat dels quals empobreix l'estructura del sòl, ECOFERT® actua en microdosis d'aminoàcids directament assimilables —sense provocar lixiviació ni augment de salinitat o de nitrats, ni a la planta ni a la terra. El producte no és inflamable, no té perill notable per a l'usuari (com a molt una lleugera irritació després d'un contacte amb la pell molt prolongat) i no planteja cap problema de transport, d'emmagatzematge ni d'expedició, inclosa la via aèria segons les normes IATA i OACI.",
            },
            {
              h: "Un protocol senzill, adaptat a cada conreu",
              p: "L'aplicació es fa al sòl o per via foliar, en general dues vegades per cicle: una abans de la floració o de la sembra, una altra a mitja campanya. Per als oliverars, dos flascons n'hi ha prou per a 90-100 arbres, un a l'hivern i un altre al setembre-octubre; en zona tropical, un flascó cada tres mesos és suficient per a la majoria de conreus. Combinat amb els hidroretenidors EVERGREEN® i ECOSORB®, ECOFERT® multiplica els seus efectes: fins a un +100 % de producció documentada a la zona saheliana.",
            },
          ],
          gallery: [
            "Amb ECOFERT®, el sistema radicular es desenvolupa en profunditat des de les primeres fases.",
            "Conreus extensius: una nutrició en microdosis, sense lixiviació cap als aqüífers.",
            "Fruiters i arboricultura: dues aplicacions l'any són suficients.",
          ],
        },
      },
      {
        id: "protection",
        num: "03",
        kicker: "Protegir sense residus",
        title: "NAPEMA®",
        text: "Natural Pest Management: una lluita contra les plagues sense química de síntesi ni molècula activa, amb efecte preventiu i curatiu, mitjançant polvorització foliar i radicular. Es formulen solucions a mida per a un problema concret.",
        facts: [
          "Cap residu al sòl, a la planta ni a l'aire",
          "Pol·linitzadors i auxiliars preservats",
          "Cotxinilla de la figuera de moro, HLB dels cítrics, nematodes",
        ],
        more: "NAPEMA® (Natural Pest Management) és un enfocament disruptiu de protecció dels conreus: ni molècules de síntesi, ni lluita biològica clàssica amb insectes auxiliars —un mètode valuós des del punt de vista ecològic, però d'eficàcia limitada, perquè els depredadors no sempre hi són en el moment ni en la quantitat necessaris, i gairebé mai no permet controlar les malalties. NAPEMA® actua mitjançant polvorització foliar i radicular, amb efecte preventiu i curatiu, contra malalties, paràsits, fongs i plagues, sense deixar residus ni al sòl, ni a la planta, ni a l'aire. La seva força real és la personalització: cada solució es formula per a un problema concret, puntual o recurrent —la cotxinilla de la figuera de moro, el citrus greening (HLB) que amenaça els cítrics, o els nematodes que afecten el tomàquet i la canya de sucre en són exemples tractats amb èxit. El resultat és una protecció que respecta la fauna i la flora útils —pol·linitzadors i auxiliars inclosos— sense alterar el cicle natural de fertilitat del sòl, a un cost accessible que protegeix, en lloc d'erosionar, la rendibilitat del conreu.",
        detail: {
          sections: [
            {
              h: "El principi",
              p: "NAPEMA® (Natural Pest Management) és un enfocament disruptiu de protecció dels conreus: ni molècules de síntesi, ni lluita biològica clàssica amb insectes auxiliars. NAPEMA® actua mitjançant polvorització foliar i radicular, amb efecte preventiu i curatiu, contra malalties, paràsits, fongs i plagues, sense deixar residus ni al sòl, ni a la planta, ni a l'aire. La seva força real és la personalització: cada solució es formula per a un problema concret —la cotxinilla de la figuera de moro, el citrus greening (HLB) dels cítrics, o els nematodes del tomàquet i de la canya de sucre en són exemples tractats amb èxit.",
            },
            {
              h: "Per què NAPEMA® va més enllà de la lluita biològica clàssica",
              p: "La lluita biològica amb insectes depredadors o parasitoides és ecològica, però resulta aleatòria: els auxiliars no sempre hi són en el moment ni en nombre suficient, i aquest mètode gairebé mai no permet controlar les malalties del vegetal. NAPEMA® s'aplica directament per polvorització foliar i radicular, amb un efecte alhora preventiu —reforçant les defenses naturals de la planta abans que apareguin els símptomes— i curatiu, eliminant ràpidament els agents patògens ja instal·lats i restaurant la vitalitat de la planta infestada.",
            },
            {
              h: "Resultats visibles en poques setmanes",
              p: "En una figuera de moro molt infestada de cotxinilles, l'aplicació de NAPEMA® segons les nostres recomanacions elimina visiblement els paràsits en quatre setmanes: la planta es recupera, sense rastre de cotxinilla, amb un creixement nou i sa. El mateix principi d'acció preventiva i curativa s'aplica al citrus greening (HLB) dels cítrics o als nematodes del tomàquet i de la canya de sucre —cada vegada, amb una solució reformulada per al problema concret trobat sobre el terreny. El resultat respecta la fauna i la flora útils, pol·linitzadors inclosos.",
            },
          ],
          gallery: [
            "Un conreu sa, protegit sense deixar el mínim residu al sòl.",
            "Aplicació per polvorització, en vegetació.",
            "Els pol·linitzadors, totalment preservats per NAPEMA®.",
          ],
        },
      },
      {
        id: "eau-restructuree",
        num: "04",
        kicker: "Reestructurar l'aigua",
        title: "Water Vital®",
        text: "La reestructuració per ressonància molecular transforma una aigua «morta», desorganitzada a escala atòmica, en aigua viva que recupera les seves propietats naturals. El sistema funciona sense energia, sense manteniment i sense consumibles.",
        facts: [
          "−30 % d'aigua, efecte immediat",
          "Fins a −70 % combinat amb els hidroretenidors",
          "Menys corrosió i calç, adoptat en 55 països",
        ],
        more: "Water Vital® reestructura l'aigua per ressonància molecular: una aigua «morta», desorganitzada a escala atòmica després de passar per canonades o pous, recupera una estructura propera a la de l'aigua natural. El sistema és purament físic —sense energia, sense manteniment, sense consumibles ni productes químics— i s'instal·la directament a la xarxa existent, a la sortida de les bombes. Sobre el terreny, al Grup EL HILAL (Sidi Moussa, Tipaza, Algèria), Water Vital® va ser la solució escollida per regar per degoteig 350 hectàrees d'arbres fruiters (figueres, pomeres, presseguers, magraners), alimentades per un embassament de 200 x 100 x 12 metres i diversos pous, a través de tres grups de bombeig amb cabals de 42 a 180 m³/h. La solució es va instal·lar directament a les sortides de les bombes, sense modificar la xarxa de reg existent. Efectes mesurats: fins a −30 % de consum d'aigua des de la posada en marxa, i fins a −70 % combinat amb els nostres hidroretenidors EVERGREEN® o ECOSORB®; menys corrosió i menys dipòsits calcaris a les canonades i als degoters. La tecnologia s'utilitza avui en 55 països.",
        detail: {
          sections: [
            {
              h: "El principi",
              p: "Water Vital® reestructura l'aigua per ressonància molecular: una aigua «morta», desorganitzada a escala atòmica després de passar per canonades o pous, recupera una estructura propera a la de l'aigua natural. El sistema és purament físic —sense energia, sense manteniment, sense consumibles ni productes químics— i s'instal·la directament a la xarxa existent, a la sortida de les bombes. Efectes mesurats: fins a −30 % de consum d'aigua des de la posada en marxa, i fins a −70 % combinat amb els nostres hidroretenidors. La tecnologia s'utilitza avui en 55 països.",
            },
            {
              h: "La ressonància molecular, explicada",
              p: "L'aigua que ha circulat molt de temps per canonades, un pou o una xarxa de reg perd la seva estructura molecular natural: es converteix en una aigua «morta», desorganitzada a escala atòmica. Water Vital® restaura aquesta estructura per ressonància, sense aportar energia, sense manteniment i sense consumibles ni productes químics —un sistema purament físic que es connecta directament a la canonada existent, a la sortida de les bombes, sense modificar la xarxa.",
            },
            {
              h: "Cas pràctic: Grup EL HILAL, Algèria",
              p: "L'agost del 2025, el nostre equip va visitar Sidi Moussa, a la província de Tipaza, a la SARL EL HILAL Desenvolupament i Agricultura Industrial. L'emplaçament: unes 350 hectàrees d'arbres fruiters (figueres, pomeres, presseguers, magraners), ja equipades amb reg per degoteig, alimentades per un embassament de reg de 200 x 100 x 12 metres i diversos pous. Tres grups de bombeig, amb cabals de 42 a 180 m³/h, reguen la finca unes quatre hores al dia. Water Vital® es va instal·lar directament a les tres sortides de bomba. Resultat: fins a −30 % de consum d'aigua des de la posada en marxa, i fins a −70 % combinat amb els nostres hidroretenidors.",
            },
          ],
          gallery: [
            "L'embassament de reg del Grup EL HILAL, 200 x 100 x 12 metres, Sidi Moussa (Algèria).",
            "L'estació de bombeig i de filtració, on es va instal·lar Water Vital®.",
            "El camp de fruiters regat per degoteig, durant la visita de l'agost del 2025.",
          ],
        },
      },
      {
        id: "paulownia",
        num: "05",
        kicker: "Plantar per durar",
        title: "Paulownia ALTIFOLIA®",
        text: "L'arbre de creixement més ràpid del món: 13 a 15 m en sis a vuit anys, fins a 20 m després, gairebé 3 m l'any. Combinat amb el nostre hidroretenidor EVERGREEN®, redueix un 50 % les seves necessitats d'aigua de reg. Varietats híbrides estèrils i no invasives, acompanyades des del planter jove fins a la venda de la fusta.",
        facts: [
          "400 a 500 arbres/ha, valorats a 400/450 € per m³",
          "Rendibilitat al llarg de sis anys de conreu",
          "Resisteix de −25 °C a +45 °C, només crema a 426 °C",
          "400 a 700 kg de mel per hectàrea, i crèdits de carboni",
        ],
        more: "El Paulownia ALTIFOLIA® és l'arbre de creixement més ràpid del món: en bones condicions arriba de 13 a 15 metres en sis a vuit anys, i fins a 20 metres després —uns 3 metres l'any— amb fulles que poden superar els 80 cm de llarg. És també un dels arbres més eficients a captar CO₂ i a alliberar oxigen per fotosíntesi. La nostra varietat ALTIFOLIA®, creuament entre Paulownia Elongata i Paulownia Fortunei, va ser seleccionada per a climes càlids: desenvolupa un tronc de gran diàmetre en molt poc temps. Combinada amb 100 g d'EVERGREEN® per planta en el moment de plantar, la necessitat de reg baixa un 50 %, sense exposar mai l'arbre a l'estrès hídric. El seu sistema radicular profund enriqueix el sòl amb nitrogen i evita l'erosió; la seva resistència natural a plagues i malalties és alta, i la fusta només s'inflama a partir de 426 °C, cosa que la converteix també en una barrera contra el foc. Els planters (25 a 30 cm en el moment del lliurament, en test, certificats lliures de malaltia, amb garantia de reposició) es transporten amb avió en 6 setmanes i després necessiten 6 setmanes d'hivernacle abans de plantar-los amb reg per degoteig. La primera tallada arriba al final del sisè any, amb una fusta valorada a 400/450 € el m³; nosaltres mateixos conreem aquesta varietat des de fa anys, especialment a Espanya.",
        detail: {
          sections: [
            {
              h: "El principi",
              p: "El Paulownia ALTIFOLIA® és l'arbre de creixement més ràpid del món: en bones condicions arriba de 13 a 15 metres en sis a vuit anys, i fins a 20 metres després —uns 3 metres l'any— amb fulles que poden superar els 80 cm de llarg. És també un dels arbres més eficients a captar CO₂ i a alliberar oxigen per fotosíntesi. La nostra varietat ALTIFOLIA® va ser seleccionada per a climes càlids: desenvolupa un tronc de gran diàmetre en molt poc temps. Combinada amb 100 g d'EVERGREEN® per planta en el moment de plantar, la necessitat de reg baixa un 50 %, sense exposar mai l'arbre a l'estrès hídric.",
            },
            {
              h: "Una selecció pensada per a climes càlids",
              p: "La nostra varietat ALTIFOLIA® es distingeix per un creixement homogeni i compacte, una copa estreta i fulles gruixudes i carnoses; la rectitud dels seus brots anuals permet, ja des del segon any, prescindir d'una poda de formació. Molt resistent a plagues i malalties gràcies al seu sistema radicular profund, també enriqueix el sòl amb nitrogen i evita l'erosió. La fusta només s'inflama a partir de 426 °C, cosa que la converteix a més en una barrera contra el foc eficaç.",
            },
            {
              h: "De la comanda a la primera collita",
              p: "Els arbres es lliuren com a planters de 25 a 30 cm, en test, transportats amb avió en un termini mitjà de sis setmanes, a partir d'una comanda mínima de 1000 unitats. Cada planta està certificada lliure de malaltia amb certificat fitosanitari i està garantida: un arbre que morís durant el creixement es reposa automàticament. En arribar, els planters passen sis setmanes a l'hivernacle abans de plantar-los, amb reg per degoteig i protecció contra la fauna. El ritme de creixement, uns tres metres l'any, permet una primera tallada ja al final del sisè any, amb una fusta valorada a 400/450 € el m³.",
            },
          ],
          gallery: [
            "El manteniment d'una plantació de Paulownia ALTIFOLIA®, a Espanya.",
            "De la plantació a la collita: set anys de creixement, fins a 20 metres.",
            "La floració del Paulownia, valuosa també per als apicultors.",
          ],
        },
      },
      {
        id: "agroforesterie",
        num: "06",
        kicker: "L'aplicació · recuperar la terra",
        title: "Agrosilvicultura i reforestació",
        text: "Ecosistemes agroforestals instal·lats en menys de 24 mesos, per a programes de reforestació i per lluitar contra la desertificació. Cada planta surt amb el seu hidroretenidor i la seva dosi de fertilitzant, perquè arreli fins i tot en sòls sorrencs o degradats.",
        facts: [
          "Ecosistema funcional en menys de 24 mesos",
          "Cada planta equipada des del moment de plantar-la",
          "Estabilització dels sòls sorrencs i degradats",
        ],
        more: "L'agrosilvicultura és el terreny on totes les nostres tecnologies es combinen. Cada programa de reforestació o de recuperació de terres degradades associa el Paulownia ALTIFOLIA® o espècies locals, els nostres hidroretenidors EVERGREEN®/ECOSORB® aportats en el moment de plantar, i els nostres fertilitzants ECOFERT® per acompanyar l'arrelament —prou per instal·lar un ecosistema agroforestal funcional en menys de 24 mesos, fins i tot en sòls sorrencs o molt degradats on l'arboricultura convencional fracassa. Cada planta surt ja equipada amb la seva dosi d'hidroretenidor, cosa que elimina el risc d'estrès hídric durant el període crític d'arrelament i puja la taxa de supervivència per sobre del 95 %. Més enllà de la fusta i dels ingressos que genera a llarg termini, aquest tipus de programa estabilitza de manera duradora els sòls contra l'erosió i la desertificació, restaura la biodiversitat subterrània i aèria, i obre l'accés a crèdits de carboni i a una producció de mel (fins a 400-700 kg per hectàrea amb el Paulownia) que diversifica els ingressos de les explotacions implicades.",
        detail: {
          sections: [
            {
              h: "El principi",
              p: "L'agrosilvicultura és el terreny on totes les nostres tecnologies es combinen. Cada programa de reforestació o de recuperació de terres degradades associa el Paulownia ALTIFOLIA® o espècies locals, els nostres hidroretenidors EVERGREEN®/ECOSORB® aportats en el moment de plantar, i els nostres fertilitzants ECOFERT® per acompanyar l'arrelament —prou per instal·lar un ecosistema agroforestal funcional en menys de 24 mesos, fins i tot en sòls sorrencs o molt degradats on l'arboricultura convencional fracassa.",
            },
            {
              h: "Un mètode, no només una plantació",
              p: "Recuperar una terra degradada no es limita a plantar-hi arbres: sense acompanyament, l'arrelament fracassa en sòls sorrencs, pobres o sotmesos a un estrès hídric sever. El nostre mètode combina sistemàticament tres peces tecnològiques des del moment de plantar —l'espècie adaptada, l'hidroretenidor que elimina el risc d'estrès hídric durant el període crític d'arrelament, i el fertilitzant que acompanya l'arrelament— per pujar la taxa de supervivència per sobre del 95 %.",
            },
            {
              h: "Més enllà de la fusta: biodiversitat i ingressos diversificats",
              p: "Un programa agroforestal ben dut restaura la microfauna i la microflora del sòl, estabilitza de manera duradora els sòls sorrencs i degradats contra l'erosió, i pot obrir l'accés a crèdits de carboni. Algunes espècies, com el Paulownia, permeten a més una producció de mel significativa —fins a 400 a 700 kg per hectàrea— que diversifica els ingressos de l'explotació durant els anys previs a la primera tallada de fusta.",
            },
          ],
          gallery: [
            "Plantació: cada planta surt equipada amb el seu hidroretenidor.",
            "Un ecosistema agroforestal organitzat, a punt per a vint anys de producció.",
            "Vista aèria d'un programa de recuperació de sòls degradats.",
          ],
        },
      },
    ],
  },
  essais: {
    eyebrow: "El que hi ha en marxa ara mateix",
    title: "Quinze assajos pilot en curs",
    lede: "Grups agroindustrials, cooperatives i dues universitats nord-americanes duen a terme actualment assajos amb les nostres tecnologies, a les seves pròpies parcel·les i amb els seus propis conreus. Aquests són, el setembre del 2026.",
    pilots: [
      { org: "Trois Rivières", place: "Martinica", crop: "Canya de sucre", tech: ["EVERGREEN®", "Water Vital®"] },
      {
        org: "Universitat de Florida, a Gainesville",
        place: "Florida, Estats Units",
        crop: "Plantació d'aurons vermells",
        tech: ["EVERGREEN®"],
      },
      {
        org: "Universitat Estatal d'Oregon, a Corvallis",
        place: "Oregon, Estats Units",
        crop: "Plantació d'avets de Douglas",
        tech: ["EVERGREEN®"],
      },
      {
        org: "AXE CAPITAL FOREST",
        place: "Regne Unit · Toledo, Espanya",
        crop: "Paulownia Phenix One",
        tech: ["EVERGREEN®", "ECOFERT®"],
      },
      {
        org: "Grup ZARROUK",
        place: "Tunísia",
        crop: "Conreu de tomàquets",
        tech: ["ECOSORB®", "ECOFERT®", "Water Vital®"],
      },
      {
        org: "FICILIA",
        place: "Còrsega, França",
        crop: "Oliveres i avellaners",
        tech: ["ECOSORB®", "ECOFERT®", "Water Vital®"],
      },
      {
        org: "Institut Moreau-Daverne",
        place: "França",
        crop: "Conreu hortícola",
        tech: ["ECOSORB®", "ECOFERT®"],
      },
      {
        org: "BEEN AGRO",
        place: "Guinea Conakry",
        crop: "Blat de moro i cacauet",
        tech: ["ECOSORB®", "ECOFERT®"],
      },
      {
        org: "Grup GOUDARAS",
        place: "Grècia",
        crop: "Plantació de castanyers",
        tech: ["EVERGREEN®", "ECOFERT®"],
      },
      {
        org: "AGRO COMPLEX",
        place: "Polònia",
        crop: "Blat de moro i patates",
        tech: ["EVERGREEN®"],
      },
      {
        org: "Institut CEHPAPE",
        place: "Haití",
        crop: "Horticultura / plàtan mascle / arròs",
        tech: ["ECOSORB®", "ECOFERT®", "EVERGREEN®", "NAPEMA®"],
      },
      { org: "EUROMEDITERRANEE", place: "Portugal", crop: "Gespa Phenix", tech: ["EVERGREEN®"] },
      {
        org: "Green Dream",
        place: "Chichaoua, Marroc",
        crop: "Clementines ecològiques (varietat Afourer), Paulownia",
        tech: ["ECOSORB®", "ECOFERT®", "Water Vital®"],
      },
      {
        org: "ARAFA Cie",
        place: "Egipte",
        crop: "Blat de moro / Trèvol / Olivera",
        tech: ["EVERGREEN®", "ECOFERT®"],
      },
      {
        org: "Eden Ecolodge — Jean-Philippe Durand",
        place: "Madagascar",
        crop: "Horticultura / Paulownia",
        tech: ["ECOSORB®", "ECOFERT®"],
      },
    ],
  },
  objections: {
    eyebrow: "El que ens pregunten primer",
    title: "Les sis preguntes que arriben abans de la comanda",
    lede: "Aquestes són les objeccions que sentim a cada primera reunió. Aquí teniu les respostes, i els documents que les sostenen.",
    items: [
      {
        q: "«Un hidroretenidor és poliacrilamida. No és perillós?»",
        a: "ECOSORB® és a base de midó de blat de moro i EVERGREEN® a base de potassi —sense sodi, sense acrilamida lliure. El laboratori Polymex, certificat ISO 9001, va mesurar l'acrilamida a ECOSORB® mitjançant UPLC/TOF-MS, piròlisi GC-MS i infraroig: contingut inferior a 3,0 µg/g, per sota del límit de quantificació del mètode. L'informe complet es pot descarregar.",
        proofLabel: "Anàlisi d'acrilamida — Polymex, desembre del 2024",
        proofHref: "/documents/analyse-acrylamide-ecosorb-polymex-2024.pdf",
      },
      {
        q: "«I les substàncies preocupants segons REACH?»",
        a: "EVERGREEN® es va sotmetre al cribratge SGS de les 233 substàncies extremadament preocupants de la llista candidata de l'Agència Europea de Substàncies i Mescles Químiques. Resultat: totes ≤ 0,1 % en massa, el llindar reglamentari.",
        proofLabel: "Cribratge REACH / SVHC — SGS, juny del 2023",
        proofHref: "/documents/screening-reach-svhc-evergreen-sgs-2023.pdf",
      },
      {
        q: "«Què queda al meu sòl al cap d'uns anys?»",
        a: "El polímer es degrada progressivament, entre un 20 i un 25 % l'any, en CO₂, aigua i compostos nitrogenats que les plantes fan servir com a nutrients. La durada d'efecte útil és de 2 a 3 anys per a ECOSORB® i de 3 a 4 anys per a EVERGREEN®. No hi ha acumulació ni risc de sobredosi.",
        proofLabel: null,
        proofHref: null,
      },
      {
        q: "«Els hidrogels que vaig provar van ofegar les meves plantes.»",
        a: "Aquest és el defecte dels productes a base de sodi: un cop hidratats formen una pasta que ofega la planta. Els d'acrilamida, allà on encara es permeten, només estan autoritzats per a conreus no alimentaris. Les nostres dues formulacions són a base de potassi, compatibles amb els conreus alimentaris i amb la microfauna del sòl.",
        proofLabel: null,
        proofHref: null,
      },
      {
        q: "«Funciona al meu sòl i amb el meu conreu?»",
        a: "La regla de dosificació és la mateixa a tot arreu: 3 grams per litre de terra útil. Els assajos en curs inclouen el blat de moro, la patata, la canya de sucre, el tomàquet, l'olivera, l'avellaner, el cacauet, el castanyer, la gespa, l'auró vermell i l'avet de Douglas, sota climes que van de Polònia a Guinea. Expliqueu-nos la vostra parcel·la i us direm què s'ha fet ja en una situació comparable.",
        proofLabel: null,
        proofHref: null,
      },
      {
        q: "«Parleu d'ecològic. Qui ho certifica?»",
        a: "SOHISCERT, organisme de control i certificació, en concepte d'insums utilitzables en producció vegetal ecològica conforme al reglament (CE) 2018/848 i al reglament (UE) 2021/1165. Certificació vigent fins al 4 de setembre del 2027.",
        proofLabel: "Certificat SOHISCERT — vàlid fins al 2027",
        proofHref: "/documents/certificat-bio-sohiscert.pdf",
      },
    ],
  },
  techChain: {
    eyebrow: "En camí",
    title: "Pensades per reforçar-se",
    lede: "Les cinc tecnologies es venen per separat, però es van concebre per reforçar-se. Cadascuna aixeca una limitació amb la qual la següent ensopegaria.",
    tagline:
      "Totes les tecnologies que oferim són ecoresponsables, sostenibles, eficients i rendibles",
    steps: [
      "Emmagatzemar l'aigua al sòl",
      "Reestructurar l'aigua de reg",
      "Nodrir amb insums certificats",
      "Protegir sense pesticida químic",
      "Plantar allà on la terra s'ha de recuperar",
      "Cada planta surt amb el seu retenidor i la seva dosi",
    ],
  },
  ctaBand: {
    eyebrow: "Un primer contacte no compromet a res",
    title: "Expliqueu-nos el vostre conreu, la vostra aigua, el vostre sòl.",
    text: "Us respondrem amb la combinació de tecnologies que correspon a la vostra parcel·la, les dosis i els assajos ja fets en situacions comparables.",
    cta1: "Parlar amb un agrònom",
    cta2: "Veure els dossiers tècnics",
  },
  reseau: {
    eyebrow: "Treballen amb nosaltres",
    title: "Una xarxa en 39 països",
    lede: "Productors, cooperatives, especialistes en tractament d'aigua, universitats i instituts de recerca, presents a cinc continents.",
    mapAriaLabel: "Mapa de la xarxa Green Solutions en 39 països",
  },
  countryStudies: {
    eyebrow: "Enfocament per país",
    title: "Dossiers pensats per a cada mercat",
    lede: "Economia agrícola, sectors, potencial de rendiment: els nostres equips preparen un estudi dedicat per a cada país on ens implantem.",
    backToSite: "Tornar al lloc web",
    callout: "Veure l'estudi: premeu el botó sota la bandera",
    notCoveredTitle: "El vostre país encara no hi és?",
    notCoveredBody:
      "Busquem socis de distribució en diverses zones. Un marc clar, acompanyament tècnic i una gamma ja provada en més de seixanta països.",
  },
  fieldTests: {
    eyebrow: "Proves de camp",
    title: "Assajos i informes",
    lede: "Els informes d'assajos independents i interns fets amb les nostres tecnologies, país per país.",
    backToSite: "Tornar al lloc web",
    items: [
      {
        title: "Palmeres datileres — Emirats Àrabs Units",
        meta: "ICBA · novembre del 2021",
        href: "/documents/field-tests/palmiers-emirats-uae-icba-2021.pdf",
        country: "emirats",
      },
      {
        title: "Síndries — Mèxic",
        meta: "Assaig de camp · 2023",
        href: "/documents/field-tests/pasteques-mexique-2023.pdf",
        country: "mexique",
      },
      {
        title: "Assaig pilot d'hidrogel — Florida",
        meta: "Klein University of Florida",
        href: "/documents/field-tests/hydrogel-floride-klein-university.pdf",
        country: "etats-unis",
      },
      {
        title: "AfriKelp — informe extern",
        meta: "Avaluació independent",
        href: "/documents/field-tests/afrikelp-rapport-externe.pdf",
        country: "afrique-du-sud",
      },
      {
        title: "Assaig d'hidrogel — Oregon, Estats Units",
        meta: "2025",
        href: "/documents/field-tests/hydrogel-oregon-2025.pdf",
        country: "etats-unis",
      },
      {
        title: "Informe estratègic — Golf Pèrsic",
        meta: "2026",
        href: "/documents/field-tests/hydrogel-golfe-persique-2026.pdf",
        country: "emirats",
      },
      {
        title: "Blat de moro — Turquia",
        meta: "TIGEM",
        href: "/documents/field-tests/mais-turquie-tigem.pdf",
        country: "turquie",
      },
      {
        title: "Canya de sucre — Java, Indonèsia",
        meta: "2024",
        href: "/documents/field-tests/canne-a-sucre-java-indonesie-2024.pdf",
        country: "indonesie",
      },
      {
        title: "Soja — hidroretenidor superabsorbent",
        meta: "Assaig comparatiu",
        href: "/documents/field-tests/soja-super-absorbant.pdf",
        country: "chine",
      },
      {
        title: "Patata — Sud-àfrica",
        meta: "2025",
        href: "/documents/field-tests/pomme-de-terre-afrique-du-sud-2025.pdf",
        country: "afrique-du-sud",
      },
      {
        title: "Cotó — estrès hídric, Turquia",
        meta: "Assaig de camp",
        href: "/documents/field-tests/coton-stress-hydrique-turquie.pdf",
        country: "turquie",
      },
    ],
  },
  partnersPage: {
    eyebrow: "Ecosistema",
    title: "Els nostres socis",
    lede: "Productors, instituts de recerca, distribuïdors i organitzacions que construeixen aquesta xarxa amb nosaltres.",
    hint: "Feu clic als logotips per veure'n el lloc web.",
    backToPartners: "← Tornar als socis",
  },
  team: {
    eyebrow: "L'empresa",
    title: "Direcció",
    tagline: "L'aliança de l'experiència i de la competència!",
    expertsEyebrow: "Experts i referents",
    direction: [
      { name: "Michel-Paul Correa", role: "Director general" },
      { name: "Jean-Michel Foucher", role: "Director tècnic" },
      { name: "Gabriel Bonnat", role: "Director d'estratègia" },
      { name: "Franck Petain", role: "Director financer" },
    ],
    experts: [
      { name: "Gilles Martin-Peulet", role: "Expert en sòls i plantes · 50+ països" },
      { name: "Christian Carnavalet", role: "Institut Moreau-Daverne · Mètode francès" },
      { name: "Pr Nicolas Marmier", role: "Professor i investigador en medi ambient" },
      { name: "René Munya", role: "President, Afrinest Farm · Sud-àfrica" },
      { name: "Chokri Bayoudh", role: "CEO, Greenfield Advisors · Tunísia" },
      { name: "Pr Mohamed Hajlaoui", role: "Professor, INAT Tunis · Director de recerca" },
      { name: "Jean-Guy Ongono", role: "Camerun · CEMAC i Àfrica" },
      { name: "Lionel Lhommet", role: "Golf Pèrsic" },
      { name: "Ken Arian", role: "Oceà Índic i Àfrica" },
      { name: "Ahmed Elashrry", role: "Egipte i Jordània" },
      { name: "Alfrédo Curina", role: "Itàlia · Especialista en tabac" },
      { name: "Jean-Camille Bissereth", role: "President, CEHPAPE · Haití i el Carib" },
      { name: "Daniel Baloche", role: "Estats Units" },
      { name: "Me Yves Haddad", role: "Advocat internacional" },
      { name: "David James", role: "Expert internacional en Paulownia · més de 20 anys d'experiència" },
      { name: "Emile Grac", role: "Assessor en Paulownia i cítrics · Marroc" },
    ],
  },
  statement: {
    eyebrow: "L'èxit no sempre és el que es veu",
    title: "L'essencial passa sota terra.",
    text: "Allò de què depèn una collita passa fora del camp de visió: l'aigua que un sòl sap retenir, la vida que encara hi ha, els residus deixats per la temporada anterior. Les nostres cinc tecnologies treballen exactament en aquesta capa, la que ningú no fotografia.",
    tag: "És aquí on treballem.",
  },
  contact: {
    eyebrow: "Contacteu-nos",
    titles: [
      "Parlem de les vostres terres",
      "Parlem de les vostres plantacions",
      "Parlem d'estalvi",
      "Parlem d'eficiència",
      "Parlem de benefici",
    ],
    lede: "Sigui quin sigui el conreu, el clima i la mida de la parcel·la, el primer pas és sempre el mateix: entendre el sòl que ja teniu. Un primer contacte no compromet a res.",
    labelEmail: "Correu electrònic",
    labelAddress: "Adreça",
    successTitle: "Missatge enviat.",
    successText: "Gràcies, us respondrem aviat. Per a qualsevol urgència, escriviu directament a",
    honeypotLabel: "No ho ompliu",
    formName: "Nom",
    formStructure: "Organització",
    formCountry: "País",
    formCity: "Ciutat",
    formCrop: "Tipus de conreu",
    formArea: "Superfície conreada",
    formEmail: "Correu electrònic",
    formMessage: "El vostre missatge",
    sending: "Enviant…",
    send: "Enviar",
    errorDefault: "L'enviament ha fallat. Torneu-ho a provar.",
    errorNetwork: "No s'ha pogut contactar amb el servidor. Comproveu la connexió i torneu-ho a provar.",
  },
  resources: {
    eyebrow: "Voleu mirar-ho de més a prop?",
    title: "Alguns documents per endur-se abans de decidir res",
    docsEyebrow: "Per descarregar ara mateix",
    cards: [
      {
        num: "01",
        title: "Dossier tècnic",
        text: "Composició, dosificació, assajos al camp i certificacions de cadascuna de les cinc tecnologies.",
      },
      {
        num: "02",
        title: "Dossier Paulownia",
        text: "Densitat de plantació, corba de creixement, sortides comercials i calendari de rendibilitat a sis anys.",
      },
      {
        num: "03",
        title: "Fer-se soci",
        text: "Distribució, representació per país, assajos conjunts: expliqueu-nos el vostre territori.",
      },
    ],
    documents: [
      {
        title: "Certificat ecològic SOHISCERT",
        meta: "Insums utilitzables en producció vegetal ecològica · vàlid fins al 4 de setembre del 2027",
      },
      {
        title: "Anàlisi d'acrilamida ECOSORB®",
        meta: "Laboratori Polymex, certificat ISO 9001 · desembre del 2024 · contingut < 3,0 µg/g",
      },
      {
        title: "Cribratge REACH / SVHC EVERGREEN®",
        meta: "SGS · juny del 2023 · 233 substàncies extremadament preocupants, totes ≤ 0,1 %",
      },
      {
        title: "Informe d'assaig ECOSORB®",
        meta: "SGS · novembre del 2024 · caracterització del polímer superabsorbent",
      },
    ],
  },
  footer: {
    address: "Green Solutions Groupe AIM SA · 46, route de la Condémine, 1475 Forel, Suïssa",
    photoCreditPrefix: "Fotos Paulownia:",
    photoCreditAnd: "i",
  },
  countries: [
    "França", "Sud-àfrica", "Tunísia", "Itàlia", "Regne Unit", "Canadà", "Espanya", "Mali",
    "Carib", "Estats Units", "Camerun", "Guinea", "Senegal", "Marroc", "Guinea Bissau", "Brasil",
    "Aràbia Saudita", "Sultanat d'Oman", "Congo", "Costa d'Ivori", "Sudan del Sud", "Polònia",
    "Grècia", "Portugal", "Emirats Àrabs Units", "Mèxic", "Turquia", "Indonèsia", "Xina", "Egipte",
    "Algèria", "Argentina", "Xile", "Gabon", "Ghana", "Jordània", "Kuwait", "Croàcia", "Madagascar",
  ],
};
