/**
 * Les pays couverts par un dossier, en un seul endroit.
 *
 * Auparavant, chaque langue portait sa propre liste de vingt-quatre entrées
 * recopiée à la main dans content.ts. Les copies avaient divergé : l'anglais
 * affichait soixante-douze boutons, dont le Maroc six fois de suite sous les
 * noms « Fas », « Marocco », « Marokko », « Maroko », « Marruecos » et
 * « Morocco » ; l'allemand, le chinois, le grec et le turc en affichaient
 * quatorze au lieu de vingt-quatre ; et la dernière entrée de chaque langue
 * avait été écrasée par la première de la suivante, si bien que la Croatie
 * s'écrivait « كرواتيا » en portugais.
 *
 * L'ordre vient d'ici, les noms viennent d'ici, et une langue ne peut plus
 * perdre ni dupliquer un pays : il n'y a plus qu'une liste.
 */

export const COUNTRY_SLUGS = [
  "cote-divoire",
  "congo",
  "ghana",
  "guinee-conakry",
  "maroc",
  "algerie",
  "afrique-du-sud",
  "gabon",
  "egypte",
  "jordanie",
  "haiti",
  "usa",
  "arabie-saoudite",
  "cameroun",
  "koweit",
  "oman",
  "senegal",
  "tunisie",
  "soudan-sud",
  "espagne",
  "grece",
  "chili",
  "argentine",
  "croatie",
] as const;

export type CountrySlug = (typeof COUNTRY_SLUGS)[number];

/**
 * Le nom de chaque pays dans chaque langue.
 *
 * Le type impose les vingt-quatre clés : ajouter un pays ci-dessus sans le
 * traduire ici ne compile pas. C'est voulu — c'est ce contrôle qui manquait.
 */
type NameTable = Record<CountrySlug, string>;

export const COUNTRY_NAMES: Record<string, NameTable> = {
  fr: {
    "cote-divoire": "Côte d'Ivoire",
    congo: "Congo",
    ghana: "Ghana",
    "guinee-conakry": "Guinée Conakry",
    maroc: "Maroc",
    algerie: "Algérie",
    "afrique-du-sud": "Afrique du Sud",
    gabon: "Gabon",
    egypte: "Égypte",
    jordanie: "Jordanie",
    haiti: "Haïti",
    usa: "États-Unis",
    "arabie-saoudite": "Arabie Saoudite",
    cameroun: "Cameroun",
    koweit: "Koweït",
    oman: "Oman",
    senegal: "Sénégal",
    tunisie: "Tunisie",
    "soudan-sud": "Soudan du Sud",
    espagne: "Espagne",
    grece: "Grèce",
    chili: "Chili",
    argentine: "Argentine",
    croatie: "Croatie",
  },
  en: {
    "cote-divoire": "Côte d'Ivoire",
    congo: "Congo",
    ghana: "Ghana",
    "guinee-conakry": "Guinea Conakry",
    maroc: "Morocco",
    algerie: "Algeria",
    "afrique-du-sud": "South Africa",
    gabon: "Gabon",
    egypte: "Egypt",
    jordanie: "Jordan",
    haiti: "Haiti",
    usa: "United States",
    "arabie-saoudite": "Saudi Arabia",
    cameroun: "Cameroon",
    koweit: "Kuwait",
    oman: "Oman",
    senegal: "Senegal",
    tunisie: "Tunisia",
    "soudan-sud": "South Sudan",
    espagne: "Spain",
    grece: "Greece",
    chili: "Chile",
    argentine: "Argentina",
    croatie: "Croatia",
  },
  es: {
    "cote-divoire": "Costa de Marfil",
    congo: "Congo",
    ghana: "Ghana",
    "guinee-conakry": "Guinea Conakri",
    maroc: "Marruecos",
    algerie: "Argelia",
    "afrique-du-sud": "Sudáfrica",
    gabon: "Gabón",
    egypte: "Egipto",
    jordanie: "Jordania",
    haiti: "Haití",
    usa: "Estados Unidos",
    "arabie-saoudite": "Arabia Saudí",
    cameroun: "Camerún",
    koweit: "Kuwait",
    oman: "Omán",
    senegal: "Senegal",
    tunisie: "Túnez",
    "soudan-sud": "Sudán del Sur",
    espagne: "España",
    grece: "Grecia",
    chili: "Chile",
    argentine: "Argentina",
    croatie: "Croacia",
  },
  pt: {
    "cote-divoire": "Costa do Marfim",
    congo: "Congo",
    ghana: "Gana",
    "guinee-conakry": "Guiné Conacri",
    maroc: "Marrocos",
    algerie: "Argélia",
    "afrique-du-sud": "África do Sul",
    gabon: "Gabão",
    egypte: "Egito",
    jordanie: "Jordânia",
    haiti: "Haiti",
    usa: "Estados Unidos",
    "arabie-saoudite": "Arábia Saudita",
    cameroun: "Camarões",
    koweit: "Kuwait",
    oman: "Omã",
    senegal: "Senegal",
    tunisie: "Tunísia",
    "soudan-sud": "Sudão do Sul",
    espagne: "Espanha",
    grece: "Grécia",
    chili: "Chile",
    argentine: "Argentina",
    croatie: "Croácia",
  },
  ar: {
    "cote-divoire": "ساحل العاج",
    congo: "الكونغو",
    ghana: "غانا",
    "guinee-conakry": "غينيا كوناكري",
    maroc: "المغرب",
    algerie: "الجزائر",
    "afrique-du-sud": "جنوب أفريقيا",
    gabon: "الجابون",
    egypte: "مصر",
    jordanie: "الأردن",
    haiti: "هايتي",
    usa: "الولايات المتحدة",
    "arabie-saoudite": "المملكة العربية السعودية",
    cameroun: "الكاميرون",
    koweit: "الكويت",
    oman: "عُمان",
    senegal: "السنغال",
    tunisie: "تونس",
    "soudan-sud": "جنوب السودان",
    espagne: "إسبانيا",
    grece: "اليونان",
    chili: "تشيلي",
    argentine: "الأرجنتين",
    croatie: "كرواتيا",
  },
  zh: {
    "cote-divoire": "科特迪瓦",
    congo: "刚果",
    ghana: "加纳",
    "guinee-conakry": "几内亚科纳克里",
    maroc: "摩洛哥",
    algerie: "阿尔及利亚",
    "afrique-du-sud": "南非",
    gabon: "加蓬",
    egypte: "埃及",
    jordanie: "约旦",
    haiti: "海地",
    usa: "美国",
    "arabie-saoudite": "沙特阿拉伯",
    cameroun: "喀麦隆",
    koweit: "科威特",
    oman: "阿曼",
    senegal: "塞内加尔",
    tunisie: "突尼斯",
    "soudan-sud": "南苏丹",
    espagne: "西班牙",
    grece: "希腊",
    chili: "智利",
    argentine: "阿根廷",
    croatie: "克罗地亚",
  },
  id: {
    "cote-divoire": "Pantai Gading",
    congo: "Kongo",
    ghana: "Ghana",
    "guinee-conakry": "Guinea Conakry",
    maroc: "Maroko",
    algerie: "Aljazair",
    "afrique-du-sud": "Afrika Selatan",
    gabon: "Gabon",
    egypte: "Mesir",
    jordanie: "Yordania",
    haiti: "Haiti",
    usa: "Amerika Serikat",
    "arabie-saoudite": "Arab Saudi",
    cameroun: "Kamerun",
    koweit: "Kuwait",
    oman: "Oman",
    senegal: "Senegal",
    tunisie: "Tunisia",
    "soudan-sud": "Sudan Selatan",
    espagne: "Spanyol",
    grece: "Yunani",
    chili: "Chili",
    argentine: "Argentina",
    croatie: "Kroasia",
  },
  de: {
    "cote-divoire": "Elfenbeinküste",
    congo: "Kongo",
    ghana: "Ghana",
    "guinee-conakry": "Guinea-Conakry",
    maroc: "Marokko",
    algerie: "Algerien",
    "afrique-du-sud": "Südafrika",
    gabon: "Gabun",
    egypte: "Ägypten",
    jordanie: "Jordanien",
    haiti: "Haiti",
    usa: "Vereinigte Staaten",
    "arabie-saoudite": "Saudi-Arabien",
    cameroun: "Kamerun",
    koweit: "Kuwait",
    oman: "Oman",
    senegal: "Senegal",
    tunisie: "Tunesien",
    "soudan-sud": "Südsudan",
    espagne: "Spanien",
    grece: "Griechenland",
    chili: "Chile",
    argentine: "Argentinien",
    croatie: "Kroatien",
  },
  it: {
    "cote-divoire": "Costa d'Avorio",
    congo: "Congo",
    ghana: "Ghana",
    "guinee-conakry": "Guinea Conakry",
    maroc: "Marocco",
    algerie: "Algeria",
    "afrique-du-sud": "Sudafrica",
    gabon: "Gabon",
    egypte: "Egitto",
    jordanie: "Giordania",
    haiti: "Haiti",
    usa: "Stati Uniti",
    "arabie-saoudite": "Arabia Saudita",
    cameroun: "Camerun",
    koweit: "Kuwait",
    oman: "Oman",
    senegal: "Senegal",
    tunisie: "Tunisia",
    "soudan-sud": "Sudan del Sud",
    espagne: "Spagna",
    grece: "Grecia",
    chili: "Cile",
    argentine: "Argentina",
    croatie: "Croazia",
  },
  el: {
    "cote-divoire": "Ακτή Ελεφαντοστού",
    congo: "Κονγκό",
    ghana: "Γκάνα",
    "guinee-conakry": "Γουινέα Κόνακρι",
    maroc: "Μαρόκο",
    algerie: "Αλγερία",
    "afrique-du-sud": "Νότια Αφρική",
    gabon: "Γκαμπόν",
    egypte: "Αίγυπτος",
    jordanie: "Ιορδανία",
    haiti: "Αϊτή",
    usa: "Ηνωμένες Πολιτείες",
    "arabie-saoudite": "Σαουδική Αραβία",
    cameroun: "Καμερούν",
    koweit: "Κουβέιτ",
    oman: "Ομάν",
    senegal: "Σενεγάλη",
    tunisie: "Τυνησία",
    "soudan-sud": "Νότιο Σουδάν",
    espagne: "Ισπανία",
    grece: "Ελλάδα",
    chili: "Χιλή",
    argentine: "Αργεντινή",
    croatie: "Κροατία",
  },
  tr: {
    "cote-divoire": "Fildişi Sahili",
    congo: "Kongo",
    ghana: "Gana",
    "guinee-conakry": "Gine Konakri",
    maroc: "Fas",
    algerie: "Cezayir",
    "afrique-du-sud": "Güney Afrika",
    gabon: "Gabon",
    egypte: "Mısır",
    jordanie: "Ürdün",
    haiti: "Haiti",
    usa: "Amerika Birleşik Devletleri",
    "arabie-saoudite": "Suudi Arabistan",
    cameroun: "Kamerun",
    koweit: "Kuveyt",
    oman: "Umman",
    senegal: "Senegal",
    tunisie: "Tunus",
    "soudan-sud": "Güney Sudan",
    espagne: "İspanya",
    grece: "Yunanistan",
    chili: "Şili",
    argentine: "Arjantin",
    croatie: "Hırvatistan",
  },
  pl: {
    "cote-divoire": "Wybrzeże Kości Słoniowej",
    congo: "Kongo",
    ghana: "Ghana",
    "guinee-conakry": "Gwinea Konakry",
    maroc: "Maroko",
    algerie: "Algieria",
    "afrique-du-sud": "Republika Południowej Afryki",
    gabon: "Gabon",
    egypte: "Egipt",
    jordanie: "Jordania",
    haiti: "Haiti",
    usa: "Stany Zjednoczone",
    "arabie-saoudite": "Arabia Saudyjska",
    cameroun: "Kamerun",
    koweit: "Kuwejt",
    oman: "Oman",
    senegal: "Senegal",
    tunisie: "Tunezja",
    "soudan-sud": "Sudan Południowy",
    espagne: "Hiszpania",
    grece: "Grecja",
    chili: "Chile",
    argentine: "Argentyna",
    croatie: "Chorwacja",
  },
  hr: {
    "cote-divoire": "Obala Bjelokosti",
    congo: "Kongo",
    ghana: "Gana",
    "guinee-conakry": "Gvineja Conakry",
    maroc: "Maroko",
    algerie: "Alžir",
    "afrique-du-sud": "Južnoafrička Republika",
    gabon: "Gabon",
    egypte: "Egipat",
    jordanie: "Jordan",
    haiti: "Haiti",
    usa: "Sjedinjene Američke Države",
    "arabie-saoudite": "Saudijska Arabija",
    cameroun: "Kamerun",
    koweit: "Kuvajt",
    oman: "Oman",
    senegal: "Senegal",
    tunisie: "Tunis",
    "soudan-sud": "Južni Sudan",
    espagne: "Španjolska",
    grece: "Grčka",
    chili: "Čile",
    argentine: "Argentina",
    croatie: "Hrvatska",
  },
};

export type CountryItem = {
  slug: CountrySlug;
  country: string;
  href: string;
};

/** Les vingt-quatre pays, nommés dans la langue demandée. */
export function countryItems(langue: string): CountryItem[] {
  const noms = COUNTRY_NAMES[langue] ?? COUNTRY_NAMES.fr;
  return COUNTRY_SLUGS.map((slug) => ({
    slug,
    country: noms[slug],
    href: `/documents/countries/${slug}.pdf`,
  }));
}
